# Generated by Django 5.0.7 on 2024-09-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_otp',
            old_name='user_id',
            new_name='user',
        ),
    ]
