# Generated by Django 5.0.7 on 2024-09-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_id_user_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hall_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='user.hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='program',
            field=models.CharField(default='wedding', max_length=100),
            preserve_default=False,
        ),
    ]
