# Generated by Django 5.0.7 on 2024-09-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_booking_hall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hall_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hall'),
        ),
    ]
