# Generated by Django 5.0.7 on 2024-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_hall_id_booking_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='evening_before',
            field=models.CharField(default='no', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='features',
            field=models.TextField(default='kitchen'),
            preserve_default=False,
        ),
    ]
